HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/Manufacturers/ManufacturerDetailsViewModel.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.Products.Commands;
using HP.ClearingCenter.Application.Products.Queries;
using HP.ClearingCenter.Infrastructure.Contracts;
using HP.ClearingCenter.Infrastructure.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HP.ClearingCenter.FrontEnd.Models.Manufacturers
{
    public class ManufacturerDetailsViewModel
    {
        private IApplicationContext app;

        public ManufacturerDetailsViewModel(IApplicationContext app)
        {
            this.app = app;
            this.Command = new AddOrUpdateManufacturerCommand();
        }

        public ManufacturerData Manufacturer { get; private set; }

        public AddOrUpdateManufacturerCommand Command { get; private set; }

        public bool IsManufacturerFound { get { return this.Manufacturer.Exists(); } }

        public bool IsAddNew { get; private set; }

        public ManufacturerDetailsViewModel Initialize(int? id = 0, bool isAddNew = false)
        {
            this.Manufacturer = this.app
                .PerformQuery(new SearchManufacturersQuery { ManufacturerId = id })
                .FirstOrDefault();

            if (this.Manufacturer.Exists())
            {
                this.Command.ManufacturerId = this.Manufacturer.Id.GetValueOrDefault();
                this.Command.Shortname = this.Manufacturer.Shortname;
                this.Command.ExternalCode = this.Manufacturer.ExternalCode;
                this.Command.Description = this.Manufacturer.Description;
            }

            this.IsAddNew = isAddNew;

            return this;
        }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/Manufacturers/ManufacturersSearchViewModel.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.Products.Queries;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HP.ClearingCenter.FrontEnd.Models.Manufacturers
{
    public class ManufacturersSearchViewModel
    {
        private IApplicationContext app;

        public ManufacturersSearchViewModel(IApplicationContext app)
        {
            this.app = app;
            this.Results = Enumerable.Empty<ManufacturerData>();
        }

        public IEnumerable<ManufacturerData> Results { get; private set; }

        public ManufacturersSearchViewModel Initialize(string term, int? page)
        {
            Page = page ?? 1;
            this.Results = this.app.PerformQuery(new SearchManufacturersQuery { Term = term,Page = this.Page,MaxRows = 5});
            return this;
        }

        public int Page { get; set; }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Controllers/ManufacturersController.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.Products.Commands;
using HP.ClearingCenter.FrontEnd.Infrastructure.Web;
using HP.ClearingCenter.FrontEnd.Models.Manufacturers;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Controllers
{
    public class ManufacturersController : SiteController
    {
        public ManufacturersController(IApplicationContext app) : base(app) { }

        public ActionResult Index()
        {
            return RedirectToAction("Search");
        }

        public ActionResult Search(string term,int? page)
        {
            return View("Search", new ManufacturersSearchViewModel(this.Application).Initialize(term,page));
        }

        public ActionResult Details(int? id)
        {
            ManufacturerDetailsViewModel model = new ManufacturerDetailsViewModel(this.Application).Initialize(id);
            if (model.IsManufacturerFound || model.IsAddNew)
            {
                return View("Details", model);
            }

            return HttpNotFound();
        }
        
        [HttpPost]
        public ActionResult Details(AddOrUpdateManufacturerCommand command)
        {
            var result = this.ProcessCommand(command);
            if (result.IsSuccessful())
            {
                return RedirectToAction("Search", new { term = command.ExternalCode });
            }

            return this.Details(command.ManufacturerId);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Details", new ManufacturerDetailsViewModel(this.Application).Initialize(isAddNew: true));
        }

    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/Manufacturers/Details.cshtml
@model HP.ClearingCenter.FrontEnd.Models.Manufacturers.ManufacturerDetailsViewModel
@using HP.ClearingCenter.Application
@{
    ViewBag.Title = Html.Translate(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturerDetails_TitleText);
}

<article>
    <header>
        <h1>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturerDetails_TitleText)</h1>
    </header>
    <p class="intro">
        @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturerDetails_IntroText)
    </p>

    <div>
        @Html.Partial("_ManufacturerData", this.Model.Command)
    </div>
</article>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval.js")
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/Manufacturers/Search.cshtml
@model HP.ClearingCenter.FrontEnd.Models.Manufacturers.ManufacturersSearchViewModel
@using HP.ClearingCenter.Application
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = Html.Translate(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturersSearch_TitleText);
}

<article>
    <header>
        <h1>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturersSearch_TitleText)</h1>
    </header>
    <p class="intro">
        @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturersSearch_IntroText)
    </p>
    @using (Html.BeginForm("Search", "Manufacturers", FormMethod.Get, new { @class = "form-horizontal" }))
    {
        <div class="control-group">
            <label for="term" class="control-label"> @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturersSearch_Name) </label>
            <div class="controls">
                <input type="text" name="term" maxlength="32" class="medium" />
                @Html.SubmitButton(HP.ClearingCenter.Application.Page.Texts, x => x.SearchButton, new { type="submit", @class="button inline primary" } )
            </div>
        </div>
    }
    @if (Model.Results != null && Model.Results.Any())
    {
        <table>
            <thead>
            <tr>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturersSearch_ExternalCode)</th>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ManufacturersSearch_Name)</th>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.Actions)</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>@item.ExternalCode</td>
                    <td>@item.Shortname</td>
                    <td>@Html.LocalizedLink(HP.ClearingCenter.Application.Page.Texts, x => x.Actions_Details, "Details", "Manufacturers", new {id = item.Id})</td>
                </tr>
            }
            </tbody>
        </table>


        if (Model.Results is IPagedList)
        {
            @Html.PagedListPager((IPagedList) Model.Results, page => Url.Action("Search", new {page}));
        }


    }
</article>

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/Manufacturers/_ManufacturerData.cshtml
@model HP.ClearingCenter.Application.Products.Commands.AddOrUpdateManufacturerCommand
@{
    var localTexts = HP.ClearingCenter.Application.Page.Texts;
}

@using (Html.BeginForm("Details", "Manufacturers"))
{
    @Html.ValidationSummary()

    <div>
        @Html.LocalizedLabelFor(x => x.ExternalCode)
        @Html.TextBoxFor(x => x.ExternalCode)
    </div>
    <div>
        @Html.LocalizedLabelFor(x => x.Shortname)
        @Html.TextBoxFor(x => x.Shortname)
    </div>
    <div>
        @Html.LocalizedLabelFor(x => x.Description)
        @Html.TextBoxFor(x => x.Description)
    </div>
    <div class="form-actions">
        @Html.HiddenFor(x => x.ManufacturerId)
        @Html.SubmitButton(localTexts, x => x.SaveButton, new { @class = "button inline primary" })
    </div>
    
}