HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/TopNavViewModel.cs
using HP.ClearingCenter.Application.Security.Services;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Models
{
    public class TopNavViewModel
    {   
        private IApplicationContext app;
        private IUserInfo user;
        
        public TopNavViewModel(IApplicationContext app)
        {
            this.app = app;
            this.user = app.GetCurrentUser();
        }

        public bool IsReceivingEnabled
        {
            get
            {
                return this.IsAccessGranted(SecureAccessRights.ReceivingProcess);
            }
        }

        public bool IsClearingEnabled
        {
            get
            {
                return this.IsAccessGranted(SecureAccessRights.ClearingProcess);
            }
        }

        public bool IsProductManagementEnabled
        {
            get
            {
                return this.IsAccessGranted(SecureAccessRights.ProductManagement);
            }
        }

        private bool IsAccessGranted(SecureAccessRights accessRights)
        {
            return this.app.AuthorizationProvider.IsAuthorized(this.user.Username, accessRights.ToString());
        }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Controllers/CategoriesController.cs
using HP.ClearingCenter.Application.Products.Commands;
using HP.ClearingCenter.FrontEnd.Infrastructure.Web;
using HP.ClearingCenter.FrontEnd.Models.Categories;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Controllers
{
    public class CategoriesController : SiteController
    {
        public CategoriesController(IApplicationContext app) : base(app) { }

        public ActionResult Index()
        {
            return RedirectToAction("Search");
        }

        public ActionResult Search(string term, int? page)
        {
            return View("Search", model: new CategoriesSearchViewModel(this.Application).Initialize(term,page));
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = new CategoryDetailsViewModel(this.Application).Initialize(id);
            if (model.IsCategoryFound)
            {
                return View("Details", model);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Details(AddOrUpdateCategoryCommand command)
        {
            var result = this.ProcessCommand(command);
            return this.Details(command.CategoryId);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Details", 
                new CategoryDetailsViewModel(this.Application).Initialize(new AddOrUpdateCategoryCommand()));
        }
        
        [HttpPost]
        public ActionResult Add(AddOrUpdateCategoryCommand command)
        {
            var result = this.ProcessCommand(command);
            if (result.IsSuccessful())
            {
                return RedirectToAction("Search", new { term = command.ExternalCode });
            }
            
            return View("Details",
                new CategoryDetailsViewModel(this.Application).Initialize(command));
        }

        [HttpPost]
        public ActionResult AddAttribute(AddCategoryAttributeCommand command)
        {
            var result = this.ProcessCommand(command);
            return RedirectToAction("Details", new { id = command.CategoryId });
        }

        [HttpPost]
        public ActionResult RemoveAttribute(RemoveCategoryAttributeCommand command)
        {
            var result = this.ProcessCommand(command);
            return RedirectToAction("Details", new { id = command.CategoryId });
        }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Controllers/ProductsController.cs
using HP.ClearingCenter.Infrastructure.Helpers;
using HP.ClearingCenter.Application.Products.Queries;
using HP.ClearingCenter.FrontEnd.Infrastructure.Web;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;
using HP.ClearingCenter.FrontEnd.Models.Products;
using HP.ClearingCenter.Application.Products.Commands;

namespace HP.ClearingCenter.FrontEnd.Controllers
{
    [Authorize]
    public class ProductsController : SiteController
    {
        public ProductsController(IApplicationContext context) : base(context) { }

        public ActionResult Index()
        {
            return RedirectToAction("Search");
        }

        public ActionResult Search(string term, int? page)
        {
            return View("Search", new ProductsSearchViewModel(this.Application).Initialize(term,page));
        }

        [HttpGet]
        public ActionResult SearchJson(string term)
        {
            //TODO: move this to an API controller
            var query = new SimpleSearchProductsQuery { Term = (term ?? string.Empty).Trim().ToUpperInvariant() };
            var results = this.Application
                .PerformQuery(query)
                .Select(x => new {
                    id = x.ToJson(),
                    value = string.Format("{0} {1} ({2})", x.Manufacturer, x.ProductName, x.ProductNumber)
                });

            return Json(results, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = new ProductDetailsViewModel(this.Application).Initialize(id);
            if (model.IsProductFound)
            {
                return View("Details", model);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Details(AddOrUpdateProductCommand command)
        {
            var result = this.ProcessCommand(command);
            return this.Details(command.ProductId);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new ProductDetailsViewModel(this.Application).Initialize(new AddOrUpdateProductCommand());
            return View("Details", model);
        }

        [HttpPost]
        public ActionResult Add(AddOrUpdateProductCommand command)
        {
            var result = this.ProcessCommand(command);
            if (result.IsSuccessful())
            {
                return this.RedirectToAction("Details", new { id = result.Response<int>() });
            }

            return View("Details",
                new ProductDetailsViewModel(this.Application).Initialize(command));
        }

        [HttpPost]
        public ActionResult CustomAttributes(SubmitProductAttributesCommand command) 
        {
            var result = this.ProcessCommand(command);
            return RedirectToAction("Details", new { id = command.ProductId });
        }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Controllers/SecureController.cs
using HP.ClearingCenter.Application.Security.Commands;
using HP.ClearingCenter.FrontEnd.Infrastructure.Web;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Controllers
{
    public class SecureController : SiteController
    {
        public SecureController(IApplicationContext app) : base(app) { }

        public ActionResult SignIn()
        {
            if (this.User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(SignInCommand command)
        {
            var result = this.ProcessCommand(command);

            if (result.IsSuccessful())
            {
                return RedirectToAction("Index", "Home");
            }

            return View("SignIn");
        }

        public ActionResult SignOut()
        {
            this.Application.AuthenticationProvider.SignOut();
            return this.RedirectToAction("SignIn");
        }

    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Controllers/TransactionsController.cs
using HP.ClearingCenter.Application.TransactionTransports.Commands;
using HP.ClearingCenter.Application.TransactionTransports.Queries;
using HP.ClearingCenter.FrontEnd.Infrastructure.Web;
using HP.ClearingCenter.FrontEnd.Models.Transactions;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Controllers
{
    [Authorize]
    public class TransactionsController : SiteController
    {   
        public TransactionsController(IApplicationContext context) : base(context) {}

        #region search

        public ActionResult Index()
        {
            return this.Search(string.Empty);
        }

        public ActionResult Search(string id)
        {
            return View("Search", new TransactionsSearchViewModel(this.Application.Query, id).Initialize());
        }

        #endregion

        #region receiving

        [HttpGet]
        public ActionResult Receiving(string id)
        {
            var model = new ReceivingViewModel(this.Application.Query).Initialize(id);

            return model.TransactionTransport != null ? 
                (ActionResult)View(model) : this.HttpNotFound();
        }

        [NoCache]
        [HttpPost]        
        public ActionResult Receiving(ReceiveProductCommand command)
        {
            var result = this.ProcessCommand(command);

            return result.IsSuccessful() ?
                RedirectToAction("Index") :
                this.Receiving(command.TransportNumber);
        }

        #endregion

        #region clearing

        [HttpGet]
        public ActionResult Clearing(string id)
        {
            var model = new ClearingViewModel(this.Application.Query).Initialize(id);

            return model.TransactionTransport != null && model.TransactionTransport.IsClearingEnabled ?
                (ActionResult)View(model) : this.HttpNotFound();
        }

        [HttpPost]
        public ActionResult Clearing(ClearReceivedProductCommand command)
        {
            var result = this.ProcessCommand(command);

            if (result.IsSuccessful())
            {
                return RedirectToAction("Clearing");
            }

            return this.Clearing(command.TransportNumber);
        }

        [HttpPost]
        public ActionResult ValidateClearingProduct(ValidateClearingProductQuery query)
        {
            return Json(this.PerformQuery(query));
        }

        #endregion
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/Shared/_DrilldownDropdown.cshtml
<div>



</div>

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>HP Clearing Center - @ViewBag.Title</title>
        <meta http-equiv="x-ua-compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8" />
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
                
        @Styles.Render("~/Content/jqueryui/themes.css")
        @Styles.Render("~/Content/styles.css")
        
        <!-- Page specific styles -->        
        @RenderSection("styles", required: false)

        @Scripts.Render("~/bundles/jquery.js")                
        @Scripts.Render("~/bundles/modernizr.js")

        @{Html.EnableUnobtrusiveJavaScript();}
    </head>
    <body>
        <div id="page-wrapper">
            <!-- BEGIN Header -->
            <div id="page-header">
			    <div id="logo">
                    <a href="http://www.hp.com/" title="Visit hp.com" style="background: transparent url(@Url.Content("~/Content/images/hp-logo.gif")) no-repeat top right !important;">Visit hp.com</a>
                    <img src="@Url.Content("~/Content/images/hp-logo-print.png")" alt="Visit hp.com">
			    </div>

			    <div id="site-title">
				    @Html.LocalizedLink(HP.ClearingCenter.Application.Page.Texts, x => x.ApplicationTitle, "Index", "Home", null, new { accesskey="1", title = "Clearing Center" })
			    </div> <!-- End #site-title -->

			    <div id="header-utility">
				    <div id="utility-links">
					    <nav>
						    <ul class="inline-list">							    
							    <li><a href="@Url.Action("SignOut", "Secure")">@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.Logout)</a>·&nbsp;&nbsp;</li>							    
						    </ul>
					    </nav>
				    </div>
			    </div>  <!-- End #header-utility --> 
                
                @Html.Partial("_TopNav")
		    </div>
            <!-- END Header -->

            <!-- BEGIN page content -->
            <div id="page-content">
                @*@Html.Partial("_SideNav", new HP.ClearingCenter.FrontEnd.Models.SideNavigationModelFactory(this).CreateInstance())*@
                <!-- BEGIN content -->
                <section id="content">
                    @RenderBody()
                </section>
                <!-- END content -->
              </div>
            <!-- END page content -->

            <!-- BEGIN footer -->
            <footer id="page-footer">
    
		        <!-- BEGIN Footer Nav -->
		        <ul>
			
			        <li><a href="@Url.Action("SignOut", "Secure")">@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.Logout)</a></li>
			        <li>|</li>
			        <li><a href="http://www8.hp.com/us/en/privacy/privacy.html">@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.PrivacyStatement)</a></li>
			        <li><a href="http://www8.hp.com/us/en/privacy/terms-of-use.html">@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.TermsOfUse)</a></li>
			        <li><a href="http://www.hp.com/">hp.com</a></li>
		        </ul>
		        <!-- END Footer Nav -->
		        <p id="copyright">©  2016 Hewlett-Packard Development Company, LP.</p>
            </footer>
            <!-- END footer -->

        </div>

        <div>
            <ul>
            @foreach (var txt in Html.DebugHelperTexts())
            {
                <li>@txt</li>
            }
            </ul>
        </div>

        <script type="text/javascript" src="@Url.Content("~/Scripts/hpexperience.utils.js")"></script>
        
        <!-- page specific scripts -->
        @RenderSection("scripts", required: false)
    </body>
</html>

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/Shared/_SideNav.cshtml
@model HP.ClearingCenter.FrontEnd.Models.NavigationModel

<!-- BEGIN Sidenav -->
<section id="sidebar">
    <nav id="sidenav">
        <ul class="topics">
            @foreach (var item in Model.LinkItems) {
                string itemClass = item.IsActive ? "active" : string.Empty;
                <li class="@itemClass"><a href="@item.LinkUrl">@item.DisplayText</a></li>                
            }
        </ul>
    </nav>
</section>
<!-- END Sidenav -->

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/Shared/_TopNav.cshtml
@{
    var appContext = DependencyResolver.Current.GetService<HP.ClearingCenter.Infrastructure.Contracts.IApplicationContext>();
    var nav = new HP.ClearingCenter.FrontEnd.Models.TopNavViewModel(appContext);
    var localTexts = HP.ClearingCenter.Application.Page.Texts;
}

<!-- BEGIN top nav -->
<div id="top-nav-new">
    @if (this.User.Identity.IsAuthenticated) {
        if (nav.IsReceivingEnabled || nav.IsClearingEnabled) {        
            <nav id="ccprocesses" class="">
		        <header> 
                    <a href="@Url.Action("Index", "Transactions")">
			            <h2>@Html.TranslateWithEditor(localTexts, x => x.Menu_Transactions)</h2>
			            <p>@Html.TranslateWithEditor(localTexts, x => x.Menu_TransactionsSubtitle)</p>
			        </a> 
		        </header>
	        </nav>
        }
        
        if (nav.IsProductManagementEnabled) {
            <nav id="productdb" class="list">
		        <header> 
                    <a href="#none">
			        <h2>@Html.TranslateWithEditor(localTexts, x => x.Menu_ProductDatabase)</h2>
			        <p>@Html.TranslateWithEditor(localTexts, x => x.Menu_ProductDatabaseSubtitle)</p>
			        </a> 
		        </header>
                
		        <div class="flyout-menu hide">
			        <div class="flyout-box">
				        <ul class="topics">
                            <li><a href="#">@Html.TranslateWithEditor(localTexts, x => x.Menu_Add)</a></li>
                            <ul class="subtopics">
                                <li><a href="@Url.Action("Add", "Categories")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Categories)</a></li>
                                <li><a href="@Url.Action("Add", "CustomAttributes")">@Html.TranslateWithEditor(localTexts, x => x.Menu_CustomAttributes)</a></li>
                                <li><a href="@Url.Action("Add", "Manufacturers")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Manufacturers)</a></li>
                                <li><a href="@Url.Action("Add", "Products")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Products)</a></li>
                            </ul>
                            <li><a href="#">@Html.TranslateWithEditor(localTexts, x => x.Menu_Manage)</a></li>
                            <ul class="subtopics">                                
				                <li><a href="@Url.Action("Index", "Categories")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Categories)</a></li>
                                <li><a href="@Url.Action("Index", "CustomAttributes")">@Html.TranslateWithEditor(localTexts, x => x.Menu_CustomAttributes)</a></li>
                                <li><a href="@Url.Action("Index", "Manufacturers")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Manufacturers)</a></li>
                                <li><a href="@Url.Action("Index", "Products")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Products)</a></li>
                            </ul>
				        </ul>
			        </div>
		        </div>
	        </nav>
            <nav id="productgroup" class="list">
		        <header> 
                    <a href="@Url.Action("Index", "ProductGroups")">
			        <h2>@Html.TranslateWithEditor(localTexts, x => x.Menu_ProductGroups)</h2>
			        <p>@Html.TranslateWithEditor(localTexts, x => x.Menu_ProductGroupsSubtitle)</p>
			        </a> 
		        </header>
		        <div class="flyout-menu hide">
			        <div class="flyout-box">
				        <ul class="topics">
                            <li><a href="@Url.Action("Add", "ProductGroups")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Add)</a></li>
                            <li><a href="@Url.Action("Index", "ProductGroups")">@Html.TranslateWithEditor(localTexts, x => x.Menu_Manage)</a></li>
				        </ul>
			        </div>
		        </div>
	        </nav>                
        }
    }
    
</div>
<!-- END top nav -->