HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/CustomAttributes/CustomAttributeDetailsViewModel.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.Data.Entities;
using HP.ClearingCenter.Application.Products.Commands;
using HP.ClearingCenter.Application.Products.Queries;
using HP.ClearingCenter.Infrastructure.Contracts;
using HP.ClearingCenter.Infrastructure.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Models.CustomAttributes
{
    public class CustomAttributeDetailsViewModel
    {
        private IApplicationContext app;

        public CustomAttributeDetailsViewModel(IApplicationContext app)
        {
            this.app = app;
            this.Command = new AddOrUpdateCustomAttributeCommand();
        }

        public IEnumerable<SelectListItem> CustomAttributeTypes {
            get
            {
                CustomAttributeType selectedValue = this.CustomAttributeData == null ? CustomAttributeType.String : this.CustomAttributeData.CustomAttributeType;
                
                yield return BuildCustomAttributeTypeItem(CustomAttributeType.String, selectedValue);
                yield return BuildCustomAttributeTypeItem(CustomAttributeType.Boolean, selectedValue);
                yield return BuildCustomAttributeTypeItem(CustomAttributeType.Integer, selectedValue);
                yield return BuildCustomAttributeTypeItem(CustomAttributeType.Decimal, selectedValue);
            }
        }

        public CustomAttributeData CustomAttributeData { get; private set; }

        public AddOrUpdateCustomAttributeCommand Command { get; private set; }
        
        public bool IsAddNew { get; private set; }

        public bool IsCustomAttributeFound
        {
            get
            {
                return CustomAttributeData.Exists();
            }
        }

        public CustomAttributeDetailsViewModel Initialize(AddOrUpdateCustomAttributeCommand command)
        {
            this.IsAddNew = true;
            this.Command = command;
            return this;
        }

        public CustomAttributeDetailsViewModel Initialize(int customAttributeId)
        {
            this.CustomAttributeData = this.app
                .PerformQuery(new GetCustomAttributeQuery { CustomAttributeId = customAttributeId })
                .FirstOrDefault();

            if (this.CustomAttributeData.Exists())
            {
                this.Command.CustomAttributeId = this.CustomAttributeData.Id;
                this.Command.CustomAttributeTypeId = ((int)this.CustomAttributeData.CustomAttributeType).ToString();
                this.Command.ExternalCode = this.CustomAttributeData.ExternalCode;
                this.Command.Shortname = this.CustomAttributeData.ShortName;
                this.Command.UnitText = this.CustomAttributeData.UnitText;
            }

            return this;
        }

        private SelectListItem BuildCustomAttributeTypeItem(CustomAttributeType customAttributeType, CustomAttributeType selectedValue)
        {
            bool isSelected = customAttributeType == selectedValue;
            return new SelectListItem { Value = ((int)customAttributeType).ToString(), Text = customAttributeType.ToString(), Selected = isSelected };
        }

    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/CustomAttributes/CustomAttributeValueViewModel.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.Data.Entities;
using HP.ClearingCenter.Infrastructure.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Models.CustomAttributes
{
    public class CustomAttributeValueViewModel
    {
        private IDictionary<string, ProductCustomAttributeValueData> values;
        private CustomAttributeData attribute;
        private int index;

        public CustomAttributeValueViewModel(CustomAttributeData attribute, int index, IDictionary<string, ProductCustomAttributeValueData> values)
        {
            this.attribute = attribute;
            this.index = index;
            this.values = values;
        }

        public HtmlString BuildExternalCodeInput()
        {
            var input = new TagBuilder("input");
            input.Attributes["name"] = this.GetIndexedName("CustomAttributeExternalCode");
            input.Attributes["type"] = "hidden";
            input.Attributes["value"] = this.attribute.ExternalCode;
            
            return new HtmlString(input.ToString());
        }

        public HtmlString BuildLabel()
        {
            var label = new TagBuilder("label");
            label.Attributes["for"] = this.GetInputName();
            label.SetInnerText(this.attribute.ShortName);

            return new HtmlString(label.ToString());
        }

        public HtmlString BuildValueInput()
        {   
            var val = this.values.ContainsKey(this.attribute.ExternalCode) ?
                this.values[this.attribute.ExternalCode] : null;

            string inputName = this.GetInputName();


            switch (this.attribute.CustomAttributeType)
            {
                case CustomAttributeType.Boolean:
                    return HandleBooleanValue(inputName, this.attribute, val);
                case CustomAttributeType.Integer:                                        
                case CustomAttributeType.Decimal:
                    var valueData = val ?? new ProductCustomAttributeValueData();
                    string numValue = this.attribute.CustomAttributeType == CustomAttributeType.Integer ?
                        valueData.IntegerValue.GetValueOrDefault().ToString(Thread.CurrentThread.CurrentCulture) :
                        valueData.DecimalValue.GetValueOrDefault().ToString("#.##", Thread.CurrentThread.CurrentCulture);
                    
                    return HandleNumericInput(inputName, this.attribute, numValue);                
            }

            return HandleStringInput(inputName, this.attribute, val);
        }

        private static HtmlString HandleNumericInput(string inputName, CustomAttributeData attr, string val) 
        {
            return new HtmlString(BuildStandardTextInput(inputName, val, attr.CustomAttributeType).ToString());
        }

        private static HtmlString HandleBooleanValue(string inputName, CustomAttributeData attr, ProductCustomAttributeValueData val)
        {
            bool existingValue = val != null ? val.BooleanValue.GetValueOrDefault() : false;
            bool[] values = new[] { true, false };
            var selectListItems = values.Select(x => new SelectListItem
            {
                Value = x.ToString().ToLowerInvariant(),
                Text = x.ToString().ToLowerInvariant(),
                Selected = existingValue == x
            });

            return new HtmlString(
                BuildSelectList(inputName, selectListItems, existingValue.ToString().ToLowerInvariant()).ToString());
        }

        private static HtmlString HandleStringInput(string inputName, CustomAttributeData attr, ProductCustomAttributeValueData val)
        {
            string existingValue = val != null ? val.StringValue : string.Empty;

            // show option list items if there are any
            if (attr.OptionListItems != null && attr.OptionListItems.Any())
            {
                var selectListItems = attr.OptionListItems
                    .Select(x => new SelectListItem
                    {
                        Text = x.DisplayText ?? x.ValueText,
                        Value = x.ValueText,
                        Selected = x.ValueText == existingValue
                    });

                return new HtmlString(
                    BuildSelectList(inputName, selectListItems, existingValue, createEmptyItem: true).ToString());
            }

            return new HtmlString(
                BuildStandardTextInput(inputName, existingValue).ToString());
        }

        private static TagBuilder BuildStandardTextInput(string inputName, string existingValue, CustomAttributeType attrType = CustomAttributeType.String)
        {
            // show a standard input control
            var input = new TagBuilder("input");
            input.Attributes["name"] = inputName;
            input.Attributes["type"] = "text";
            input.Attributes["value"] = existingValue;

            bool isNumeric = attrType == CustomAttributeType.Integer || attrType == CustomAttributeType.Decimal;
            if (isNumeric)
            {
                input.Attributes["class"] = "numeric";
                input.Attributes["type"] = "number";
                input.Attributes["min"] = "0";
                input.Attributes["data-val"] = true.ToString().ToLowerInvariant();
                input.Attributes["data-val-number"] = "Input must be a number";
                input.Attributes["step"] = attrType == CustomAttributeType.Integer ?
                    "1" : "0.01";
            }

            return input;
        }

        private static TagBuilder BuildSelectList(string inputName, IEnumerable<SelectListItem> items, string selectedValue, bool createEmptyItem = false)
        {
            if (items == null || !items.Any()) return BuildStandardTextInput(inputName, selectedValue);            
            
            var options = new StringBuilder();

            if (createEmptyItem)
            {
                options.AppendLine("<option value=\"\"></option>");
            }

            foreach (var item in items)
            {
                var opt = new TagBuilder("option");
                opt.Attributes["value"] = item.Value;
                if (item.Selected)
                {
                    opt.Attributes["selected"] = "selected";
                }

                opt.SetInnerText(item.Text);
                options.AppendLine(opt.ToString());
            }

            var select = new TagBuilder("select");
            select.Attributes["name"] = inputName;
            select.InnerHtml = options.ToString();

            return select;
        }

        private string GetIndexedName(string propertyName)
        {
            return "Values[{0}].{1}".WithTokens(this.index, propertyName);
        }

        private string GetInputName()
        {
            switch (this.attribute.CustomAttributeType)
            {
                case CustomAttributeType.Boolean:
                    return this.GetIndexedName("BooleanValue");
                case CustomAttributeType.Integer:
                    return this.GetIndexedName("IntegerValue");
                case CustomAttributeType.Decimal:
                    return this.GetIndexedName("DecimalValue");
            }

            return this.GetIndexedName("StringValue");
        }
        
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/CustomAttributes/CustomAttributesSearchViewModel.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.Products.Queries;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HP.ClearingCenter.FrontEnd.Models.CustomAttributes
{
    public class CustomAttributesSearchViewModel
    {
        private IApplicationContext app;

        public CustomAttributesSearchViewModel(IApplicationContext app)
        {
            this.app = app;
        }

        public IEnumerable<CustomAttributeData> Results { get; private set; }

        public CustomAttributesSearchViewModel Initialize(string term,int? page)
        {
            Page = page ?? 1;

            this.Results = this.app
                .PerformQuery(new GetCustomAttributeQuery { ExternalCode = term,Page = Page,MaxRowCount = 5});

            return this;
        }

        public int Page { get; set; }

    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Controllers/CustomAttributesController.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.ProductGroups.Entities;
using HP.ClearingCenter.Application.Products.Commands;
using HP.ClearingCenter.Application.Products.Queries;
using HP.ClearingCenter.FrontEnd.Infrastructure.Web;
using HP.ClearingCenter.FrontEnd.Models.CustomAttributes;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Controllers
{
    public class CustomAttributesController : SiteController
    {
        public CustomAttributesController(IApplicationContext app) : base(app) { }

        public ActionResult Index()
        {
            return RedirectToAction("Search");
        }

        public ActionResult Search(string term,int? page)
        {
            return View("Search", 
                new CustomAttributesSearchViewModel(this.Application).Initialize(term,page));
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Details", new CustomAttributeDetailsViewModel(this.Application).Initialize(new AddOrUpdateCustomAttributeCommand()));
        }

        [HttpPost]
        public ActionResult Add(AddOrUpdateCustomAttributeCommand command)
        {
            var result = this.ProcessCommand(command);
            if (result.IsSuccessful())
            {
                return RedirectToAction("Search", new { term = command.ExternalCode });
            }

            return View("Details", new CustomAttributeDetailsViewModel(this.Application)
                .Initialize(new AddOrUpdateCustomAttributeCommand()));
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = new CustomAttributeDetailsViewModel(this.Application).Initialize(id);
            if (model.IsCustomAttributeFound)
            {
                return View("Details", model);
            }

            return this.HttpNotFound();
        }

        [HttpPost]
        public ActionResult Details(AddOrUpdateCustomAttributeCommand command)
        {
            var result = this.ProcessCommand(command);

            if (result.IsSuccessful()) {
                return RedirectToAction("Details", new { id = command.CustomAttributeId });
            }

            return View("Details", new CustomAttributeDetailsViewModel(this.Application).Initialize(command.CustomAttributeId));
        }

        [HttpGet]
        public ActionResult DetailsJson(int customAttributeId)
        {
            //TODO: Move this to an API Controller
            CustomAttributeData result = this.Application
                .PerformQuery(new GetCustomAttributeQuery { CustomAttributeId = customAttributeId })
                .FirstOrDefault();

            if (result == null) return HttpNotFound();

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/CustomAttributes/Details.cshtml
@model HP.ClearingCenter.FrontEnd.Models.CustomAttributes.CustomAttributeDetailsViewModel
@using HP.ClearingCenter.Application
@{
    ViewBag.CustomAttributeDetailsView = this.Model;
    ViewBag.Title = "Details";
    ViewBag.AvailableDataTypes = this.Model.CustomAttributeTypes;
}

<article>
    <header>
        <h1>@Html.Translate(HP.ClearingCenter.Application.Page.Texts, x => x.CustomAttributeDetails_TitleText)</h1>
    </header>
    <p class="intro">
        @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.CustomAttributeDetails_IntroText)
    </p>

    <div>
        @Html.Partial("_CustomAttributeData", this.Model.Command)
    </div>
</article>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval.js")
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/CustomAttributes/Search.cshtml
@using PagedList
@using PagedList.Mvc
@model HP.ClearingCenter.FrontEnd.Models.CustomAttributes.CustomAttributesSearchViewModel
@{
    ViewBag.Title = Html.Translate(HP.ClearingCenter.Application.Page.Texts, x => x.CustomAttributesSearch_TitleText); 
    var localTexts = HP.ClearingCenter.Application.Page.Texts;
}

<article>
    <header>
        <h1>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.CustomAttributesSearch_TitleText)</h1>
    </header>
    <p class="intro">
        @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.CustomAttributesSearch_TitleText)
    </p>
    @using (Html.BeginForm("Search", "CustomAttributes", FormMethod.Get, new { @class="form-horizontal"})) 
    {
        <div class="control-group">
            <label for="term" class="control-label"> @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.CustomAttributesSearch_ShortCode) </label>
            <div class="controls">
                <input type="text" name="term" maxlength="32" class="medium" />
                @Html.SubmitButton(HP.ClearingCenter.Application.Page.Texts, x => x.SearchButton, new { type="submit", @class = "button inline primary" } )
            </div>
        </div>
    }
    @if (Model.Results != null && Model.Results.Any())
    {
        <table>
            <thead>
            <tr>
                <th>@Html.TranslateWithEditor(localTexts, x => x.CustomAttributesSearch_ShortCode)</th>
                <th>@Html.TranslateWithEditor(localTexts, x => x.CustomAttributesSearch_ShortName)</th>
                <th>@Html.TranslateWithEditor(localTexts, x => x.CustomAttributesSearch_DataType)</th>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.Actions)</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>@item.ExternalCode</td>
                    <td>@item.ShortName</td>
                    <td>@item.CustomAttributeType.ToString()</td>
                    <td>@Html.ActionLink("Details", "Details", new {controller = "CustomAttributes", id = item.Id})</td>
                </tr>
            }
            </tbody>
        </table>
       
        if (Model.Results is IPagedList)
        {
            @Html.PagedListPager((IPagedList) Model.Results, page => Url.Action("Search", new {page}));
        }
        
    }

</article>

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/CustomAttributes/_CustomAttributeData.cshtml
@model HP.ClearingCenter.Application.Products.Commands.AddOrUpdateCustomAttributeCommand
@{
    var localTexts = HP.ClearingCenter.Application.Page.Texts;
    IEnumerable<SelectListItem> availableDataTypes = (IEnumerable<SelectListItem>)ViewBag.AvailableDataTypes;
    string action = ViewBag.CustomAttributeDetailsView.IsAddNew ? "Add" : "Details";
}

@using (Html.BeginForm(action, "CustomAttributes"))
{
    @Html.ValidationSummary()
    <div>
        @Html.LocalizedLabelFor(x => x.ExternalCode)
        @Html.TextBoxFor(x => x.ExternalCode, new { @class = "medium" })
    </div>
    <div>
        @Html.LocalizedLabelFor(x => x.Shortname)
        @Html.TextBoxFor(x => x.Shortname, new { @class = "medium" })
    </div>
    <div>
        @Html.LocalizedLabelFor(x => x.UnitText)
        @Html.TextBoxFor(x => x.UnitText, new { @class = "medium" }) 
    </div>
    <div>
        @Html.LocalizedLabelFor(x => x.CustomAttributeTypeId)
        @Html.DropDownListFor(x => x.CustomAttributeTypeId, availableDataTypes, new { @class = "medium" })
    </div>
    <div class="form-actions">
        @Html.HiddenFor(x => x.CustomAttributeId)
        @Html.SubmitButton(localTexts, x => x.SubmitButton, new { @class = "button inline primary" })
    </div>
}