HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/ProductGroups/ProductGroupDetailsViewModel.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.ProductGroups.Commands;
using HP.ClearingCenter.Application.ProductGroups.Queries;
using HP.ClearingCenter.Application.Products.Queries;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HP.ClearingCenter.FrontEnd.Models.ProductGroups
{
    public class ProductGroupDetailsViewModel
    {
        private IApplicationContext app;
        
        public ProductGroupDetailsViewModel(IApplicationContext app, bool isAddingNewGroup = false)
        {
            this.app = app;
            this.IsAddingNewGroup = isAddingNewGroup;
            this.Categories = Enumerable.Empty<CategoryData>();
            this.AssignedCategories = Enumerable.Empty<CategoryData>();
        }

        public int? ProductGroupId { get; private set; }

        public bool IsAddingNewGroup { get; private set; }

        public bool IsProductGroupFound { get; private set; }

        public AddProductGroupCommand AddProductGroupCommand { get; set; }

        public AddProductGroupFilterCategoryCommand AddProductGroupFilterCategoryCommand { get; set; }

        public IEnumerable<CategoryData> Categories { get; private set; }

        public IEnumerable<CategoryData> AssignedCategories { get; private set; }

        public IEnumerable<CustomAttributeData> AvailableCategoryFilters
        {
            get
            {
                var results = new Dictionary<string, CustomAttributeData>();
                
                var categories = this.AssignedCategories ?? Enumerable.Empty<CategoryData>();
                foreach (var cat in categories)
                {
                    var attrs = cat.AvailableFilters ?? Enumerable.Empty<CustomAttributeData>();
                    foreach (var attr in attrs)
                    {
                        if (!results.ContainsKey(attr.ExternalCode))
                        {
                            results.Add(attr.ExternalCode, attr);
                        }
                    }
                }

                return results.Values
                    .OrderBy(x => x.ShortName)
                    .ToList();
            }
        }

        public ProductGroupDetailsViewModel Initialize(AddProductGroupCommand command)
        {
            this.AddProductGroupCommand = command ?? new AddProductGroupCommand();
            this.IsAddingNewGroup = true;
            return this;
        }

        public ProductGroupDetailsViewModel Initialize(ProductGroupSearchQuery query) 
        {
            query.Term = null;

            ProductGroupData pg = this.app
                .PerformQuery(query)
                .FirstOrDefault();

            if (pg != null)
            {
                this.ProductGroupId = pg.Id;
                this.AddProductGroupCommand = new AddProductGroupCommand
                {
                    ProductGroupId = pg.Id,
                    MarketingProgramId = pg.MarketingProgramId,
                    CountryIsoCode = pg.CountryIsoCode,
                    ExternalCode = pg.ExternalCode,
                    ShortName = pg.ShortName,
                    Description = pg.Description,
                    IsActive = pg.IsActive,
                };

                this.AddProductGroupFilterCategoryCommand = new AddProductGroupFilterCategoryCommand
                {
                    ProductGroupId = pg.Id
                };

                this.InitializeCategoryAttributes(pg);

                this.IsProductGroupFound = true;
            }

            this.Categories = this.app.PerformQuery(new ProductCategorySearchQuery());

            return this;
        }

        private void InitializeCategoryAttributes(ProductGroupData pg)
        {
            this.AssignedCategories = this.app.PerformQuery(new GetProductCategoryFiltersQuery 
            { 
                ProductGroupId = pg.Id
            });
        }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Models/ProductGroups/ProductGroupsSearchViewModel.cs
using HP.ClearingCenter.Application.Data.Dto;
using HP.ClearingCenter.Application.ProductGroups.Queries;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HP.ClearingCenter.FrontEnd.Models.ProductGroups
{
    public class ProductGroupsSearchViewModel
    {
        private IApplicationContext app;

        public ProductGroupsSearchViewModel(IApplicationContext app)
        {
            this.app = app;
        }

        public IEnumerable<ProductGroupData> Results { get; private set; }

        public ProductGroupsSearchViewModel Initialize(string term, int? page)
        {
            Page = page ?? 1;

            this.Results = this.app.PerformQuery(new ProductGroupSearchQuery { Term = term,Page = this.Page, MaxRowCount = 1});
            return this;
        }

        public int Page { get; set; }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Controllers/ProductGroupsController.cs
using HP.ClearingCenter.Application.ProductGroups.Commands;
using HP.ClearingCenter.Application.ProductGroups.Queries;
using HP.ClearingCenter.FrontEnd.Infrastructure.Web;
using HP.ClearingCenter.FrontEnd.Models.ProductGroups;
using HP.ClearingCenter.Infrastructure.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HP.ClearingCenter.FrontEnd.Controllers
{
    [Authorize]
    public class ProductGroupsController : SiteController
    {
        public ProductGroupsController(IApplicationContext app) : base(app) { }

        #region search

        public ActionResult Index()
        {
            return this.Search(null,1);
        }

        [HttpGet]
        public ActionResult Search(string term,int? page)
        {
            return View("Search", new ProductGroupsSearchViewModel(this.Application).Initialize(term,page));
        }

        #endregion

        #region Add/edit

        [HttpGet]
        public ActionResult Add()
        {
            return View("Details", 
                new ProductGroupDetailsViewModel(this.Application).Initialize(new AddProductGroupCommand()));
        }

        [HttpPost]
        public ActionResult Add(AddProductGroupCommand command)
        {
            command.ProductGroupId = null;
            command.IsActive = true;
            
            return this.Edit(command);
        }

        [HttpPost]
        public ActionResult Edit(AddProductGroupCommand command)
        {
            var result = this.ProcessCommand(command);

            if (result.IsSuccessful())
            {
                return command.ProductGroupId.HasValue ?
                    this.RedirectToAction("Details", new { id = command.ProductGroupId, externalCode = command.ExternalCode }) :
                    this.RedirectToAction("Index");
            }

            // show errors if any
            return View("Details",
                new ProductGroupDetailsViewModel(this.Application, isAddingNewGroup: true).Initialize(command));
        }

        #endregion

        [HttpGet]
        public ActionResult Details(int id, string externalCode)
        {
            var model = new ProductGroupDetailsViewModel(this.Application)
                .Initialize(new ProductGroupSearchQuery { Id = id, Term = externalCode });

            if (!model.IsProductGroupFound) return this.HttpNotFound();

            return View("Details", model);
        }

        [HttpPost]
        public ActionResult AddCategory(AddProductGroupFilterCategoryCommand command)
        {
            var result = this.ProcessCommand(command);
            return this.RedirectToAction("Details", new { id = command.ProductGroupId });
        }

        [HttpPost]
        public ActionResult RemoveCategory(RemoveCategoryCommand command)
        {
            this.ProcessCommand(command);
            return Json(true);
        }

        [HttpPost]
        public ActionResult AddCategoryAttributeFilter(AddCategoryAttributeFilterCommand command)
        {
            var result = this.ProcessCommand(command);
            return this.RedirectToAction("Details", new { id = command.ProductGroupId, externalCode = command.ProductGroupExternalCode });
        }

        [HttpPost]
        public ActionResult RemoveCategoryAttributeFilter(RemoveCategoryAttributeFilterCommand command)
        {
            var result = this.ProcessCommand(command);
            return this.RedirectToAction("Details", new { id = command.ProductGroupId, externalCode = command.ProductGroupExternalCode });
        }
    }
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/ProductGroups/Details.cshtml
@model HP.ClearingCenter.FrontEnd.Models.ProductGroups.ProductGroupDetailsViewModel
@using HP.ClearingCenter.Application
@{  
    ViewBag.Title = Html.Translate(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupDetails_TitleText);
    ViewBag.IsAddingNewGroup = this.Model.IsAddingNewGroup;
    ViewBag.ProductGroupId = this.Model.ProductGroupId;
    ViewBag.Categories = this.Model.Categories;
    ViewBag.ProductGroupId = this.Model.ProductGroupId;
    ViewBag.ProductGroupExternalCode = this.Model.AddProductGroupCommand != null ? this.Model.AddProductGroupCommand.ExternalCode : string.Empty;
}

@section styles {
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/styles/fg.menu.css")" />
}

<article>
    <header>
        <h1>@Html.Translate(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupDetails_TitleText)</h1>
    </header>
    <p class="intro">
        @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupDetails_IntroText)
    </p>

    <div>
        <h2>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupDetails_BasicData)</h2>
        <div>
            @Html.Partial("_ProductGroupData", this.Model.AddProductGroupCommand)
        </div>
    </div>

    @if (!this.Model.IsAddingNewGroup) {
        <div>
            <h2>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupDetails_CategoryFilters)</h2>
            <div>
                @Html.Partial("_CategoryFilters", this.Model)
            </div>
        </div>
    }

</article>

@section scripts {
    @Scripts.Render("~/bundles/jqueryui.js")
    @Scripts.Render("~/bundles/jqueryval.js")
    <script type="text/javascript" src="@Url.Content("~/Scripts/Application/Controls/fg.menu.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Application/Views/ProductGroupDetailsView.js")"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var view = new ProductGroupDetailsView({
                getAttributeDetailsUrl: '@Url.Action("DetailsJson", new { controller = "CustomAttributes" })',
                addCategoryAttributeFilterUrl: '@Url.Action("AddCategoryAttributeFilter", "ProductGroups")',
                removeCategoryUrl: '@Url.Action("RemoveCategory", "ProductGroups")'
            });

            view.show();
        });
    </script>
}

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/ProductGroups/Search.cshtml
@model HP.ClearingCenter.FrontEnd.Models.ProductGroups.ProductGroupsSearchViewModel
@using HP.ClearingCenter.Application
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = Html.Translate(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupsSearch_TitleText);
}

<article>
    <header>
        <h1>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupsSearch_TitleText)</h1>
    </header>
    <p class="intro">
        @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupsSearch_IntroText)
    </p>
    @using (Html.BeginForm("Search", "ProductGroups", FormMethod.Get, new { @class = "form-horizontal" }))
    {
        <div class="control-group">
            <label for="term" class="control-label"> @Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupsSearch_ExternalCode) </label>
            <div class="controls">
                <input type="text" name="term" maxlength="32" class="medium" />
                @Html.SubmitButton(HP.ClearingCenter.Application.Page.Texts, x => x.SearchButton, new { type="submit", @class = "button inline primary" } )
            </div>
        </div>
    }

    @if (Model.Results != null && Model.Results.Any())
    {
        <table>
            <thead>
            <tr>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupsSearch_MarketingProgram)</th>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupsSearch_ExternalCode)</th>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupsSearch_ShortName)</th>
                <th>@Html.TranslateWithEditor(HP.ClearingCenter.Application.Page.Texts, x => x.Actions)</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>@item.MarketingProgramId - @item.CountryIsoCode</td>
                    <td>@item.ExternalCode</td>
                    <td>@item.ShortName</td>
                    <td>
                        @Html.LocalizedLink(HP.ClearingCenter.Application.Page.Texts, x => x.Actions_Details, "Details", "ProductGroups", new {id = item.Id, externalCode = item.ExternalCode})
                    </td>
                </tr>
            }
            </tbody>
        </table>
        
        if (Model.Results is IPagedList)
        {
            @Html.PagedListPager((IPagedList)Model.Results, page => Url.Action("Search", new { page }));
        }
    }

</article>

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/ProductGroups/_CategoryFilterDefinition.cshtml
@model HP.ClearingCenter.Application.Data.Dto.CategoryData
@{
    var localTexts = HP.ClearingCenter.Application.Page.Texts;
    var availableAttributes = new List<SelectListItem>();
    availableAttributes.Add(new SelectListItem());
    availableAttributes.AddRange(Model.AvailableFilters.Select(x => new SelectListItem
    {
        Text = x.ShortName,
        Value = x.Id.ToString()
    }));
}

<div>
    <div>
        <h2 style="display:inline; padding-right:10px;">@this.Model.ShortName</h2>
        <a class="removeCategoryLink" href="javascript:void(0)" data-productgroupcategory-id="@Model.ProductGroupCategoryId" data-category-id="@Model.Id" data-productgroup-id="@ViewBag.ProductGroupId">Remove</a>
    </div>
    <table width="720px">
        <tbody>
            @foreach (var item in Model.Filters)
            {
                <tr>
                    <td class="attribute">@item.AttributeShortName</td>
                    <td class="operator">@item.OperatorShortName</td>
                    <td class="values">
                        @if (item.FilterOperator == HP.ClearingCenter.Application.ProductGroups.Entities.FilterOperator.Between) {
                            @item.Values[0] 
                            if (item.Values.Length > 1) {
                                <span>and</span> @item.Values[1]
                            }
                        } else {
                            @item.ValuesCsv   
                        }
                    </td>
                    <td class="actions">
                        @using (Html.BeginForm("RemoveCategoryAttributeFilter", "ProductGroups")) {
                            @Html.Hidden("ProductGroupId", (int)ViewBag.ProductGroupId)
                            @Html.Hidden("ProductGroupExternalCode", (string)ViewBag.ProductGroupExternalCode)
                            @Html.Hidden("ProductFilterId", item.ProductFilterId)
                            @Html.SubmitButton(HP.ClearingCenter.Application.Page.Texts, x => x.ProductGroupDetails_RemoveAttributeFilter, new { @class = "button slim inline secondary"})
                        }
                    </td>
                </tr>
            }
            @if (Model.AvailableFilters.Any()) {
                string selectedAttributeId = "selectedAttribute_" + Model.Id;
                string filterAttributeOperatorId = "filterAttributeOperator_" + Model.Id;
                string filterAttributeValuesId = "filterAttributeValues_" + Model.Id;
                <tr class="addFilterAttributeForm">
                    <td class="attribute">                        
                        @Html.DropDownList("CustomAttributeId", availableAttributes, new { id = selectedAttributeId, @class = "attributeSelector", categoryId = Model.Id, @operator = filterAttributeOperatorId }) 
                    </td>
                    <td class="operator">@Html.DropDownList("FilterOperatorId", Enumerable.Empty<SelectListItem>(), new { id = filterAttributeOperatorId, style = "display:none;", @class = "operatorSelector" })</td>
                    <td class="values" id="@filterAttributeValuesId">
                    </td>
                    <td class="actions">
                        @Html.Hidden("ProductGroupCategoryId", Model.ProductGroupCategoryId)
                        @Html.Hidden("ProductGroupId", (int)ViewBag.ProductGroupId)
                        @Html.Hidden("ProductGroupExternalCode", (string)ViewBag.ProductGroupExternalCode)
                        @Html.Hidden("CategoryId", Model.Id)
                        <button type="submit" class="button slim inline secondary" style="display:none;">@Html.TranslateWithEditor(localTexts, x => x.ProductGroupDetails_AddFilter)</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/ProductGroups/_CategoryFilters.cshtml
@model HP.ClearingCenter.FrontEnd.Models.ProductGroups.ProductGroupDetailsViewModel
@{
    var localTexts = HP.ClearingCenter.Application.Page.Texts;
    var categories = (IEnumerable<HP.ClearingCenter.Application.Data.Dto.CategoryData>)ViewBag.Categories;
    var categoryListBuilder = new HP.ClearingCenter.FrontEnd.Models.Categories.CategorySelectListBuilder(null, categories, false);
    
    
    string addCategoryUrl = Url.Action("AddCategory", "ProductGroups");
}
<div>
    @using (Html.BeginForm("AddCategory", "ProductGroups")) 
    {
        <div>
            @Html.Hidden("ProductGroupId", Model.AddProductGroupFilterCategoryCommand.ProductGroupId)
            <label for="CategoryExternalCode">Add Category</label>
            @categoryListBuilder.Build("CategoryId")            
            @Html.SubmitButton(localTexts, x => x.ProductGroupDetails_AddCategoryButton, new { @class = "button inline secondary" })
        </div>        
    }
</div>

<div>
    <!-- show categories here -->
    @foreach (var item in this.Model.AssignedCategories)
    {
        <!-- categories -->
        @Html.Partial("_CategoryFilterDefinition", item);
    }
</div>

HP.ClearingCenter/HP.ClearingCenter.FrontEnd/Views/ProductGroups/_ProductGroupData.cshtml
@model HP.ClearingCenter.Application.ProductGroups.Commands.AddProductGroupCommand
@{
    var localTexts = HP.ClearingCenter.Application.Page.Texts;
    string action = Model.ProductGroupId.HasValue ? "Edit" : "Add";
}
<div>
    @using (Html.BeginForm(action, "ProductGroups", FormMethod.Post))
    {
        @Html.ValidationSummary()

        <div>
            @Html.LocalizedLabelFor(x => x.MarketingProgramId)
            @Html.TextBoxFor(x => x.MarketingProgramId)
        </div>
        <div>
            @Html.LocalizedLabelFor(x => x.CountryIsoCode)
            @Html.TextBoxFor(x => x.CountryIsoCode)
        </div>
        <div>
            @Html.LocalizedLabelFor(x => x.ExternalCode)
            @Html.TextBoxFor(x => x.ExternalCode)
        </div>
        <div>
            @Html.LocalizedLabelFor(x => x.ShortName)
            @Html.TextBoxFor(x => x.ShortName)
        </div>
        <div>
            @Html.LocalizedLabelFor(x => x.Description)
            @Html.TextAreaFor(x => x.Description)
        </div>
        
        if (!ViewBag.IsAddingNewGroup) {
            
            <div>
                @Html.LocalizedLabelFor(x => x.IsActive)
                @Html.CheckBoxFor(x => x.IsActive)
            </div>
            
            <div>
                @Html.HiddenFor(x => x.ProductGroupId)
            </div>
        }
        
        <div class="form-actions">
            @Html.SubmitButton(localTexts, x => x.SaveButton, new { @class="button inline primary" })
        </div>
    }
</div>